/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 21/12/2020 11:53:55
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            64000000
#define MX_HSE_VALUE                            25000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_PLLDSIFreq_Value                     500000000
#define MX_SYSCLKFreq_VALUE                     400000000
#define MX_HCLKFreq_Value                       200000000
#define MX_CortexFreq_Value                     400000000
#define MX_APB1Freq_Value                       100000000
#define MX_APB2Freq_Value                       100000000
#define MX_CECFreq_Value                        32000
#define MX_RTCFreq_Value                        32000
#define MX_USBFreq_Value                        400000000
#define MX_WatchDogFreq_Value                   32000
#define MX_DSIFreq_Value                        96000000
#define MX_DSIPHYCLKFreq_Value                  96000000
#define MX_DSITXEscFreq_Value                   20000000
#define MX_SPDIFRXFreq_Value                    400000000
#define MX_MCO1PinFreq_Value                    64000000
#define MX_MCO2PinFreq_Value                    400000000

/*-------------------------------- CORTEX_M4  --------------------------------*/

#define MX_CORTEX_M4                            1

/* GPIO Configuration */

/*-------------------------------- NVIC1      --------------------------------*/

#define MX_NVIC1                                1

/* GPIO Configuration */

/*-------------------------------- NVIC2      --------------------------------*/

#define MX_NVIC2                                1

/* GPIO Configuration */

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/*-------------------------------- CORTEX_M7  --------------------------------*/

#define MX_CORTEX_M7                            1

/* GPIO Configuration */

/*-------------------------------- ETH        --------------------------------*/

#define MX_ETH                                  1

/* GPIO Configuration */

/* Pin PB0 */
#define MX_ETH_RXD2_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_ETH_RXD2_Pin                         PB0
#define MX_ETH_RXD2_GPIOx                       GPIOB
#define MX_ETH_RXD2_GPIO_PuPd                   GPIO_NOPULL
#define MX_MII_RXD2                             ETH_RXD2
#define MX_ETH_RXD2_GPIO_Pin                    GPIO_PIN_0
#define MX_ETH_RXD2_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_RXD2_GPIO_Mode                   GPIO_MODE_AF_PP
#define MX_ETH_RXD2_PinAttribute                CortexM7

/* Pin PB1 */
#define MX_ETH_RXD3_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_ETH_RXD3_Pin                         PB1
#define MX_ETH_RXD3_GPIOx                       GPIOB
#define MX_ETH_RXD3_GPIO_PuPd                   GPIO_NOPULL
#define MX_MII_RXD3                             ETH_RXD3
#define MX_ETH_RXD3_GPIO_Pin                    GPIO_PIN_1
#define MX_ETH_RXD3_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_RXD3_GPIO_Mode                   GPIO_MODE_AF_PP
#define MX_ETH_RXD3_PinAttribute                CortexM7

/* Pin PE2 */
#define MX_ETH_TXD3_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_ETH_TXD3_Pin                         PE2
#define MX_ETH_TXD3_GPIOx                       GPIOE
#define MX_ETH_TXD3_GPIO_PuPd                   GPIO_NOPULL
#define MX_MII_TXD3                             ETH_TXD3
#define MX_ETH_TXD3_GPIO_Pin                    GPIO_PIN_2
#define MX_ETH_TXD3_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_TXD3_GPIO_Mode                   GPIO_MODE_AF_PP
#define MX_ETH_TXD3_PinAttribute                CortexM7

/* Pin PC4 */
#define MX_ETH_RXD0_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_ETH_RXD0_Pin                         PC4
#define MX_ETH_RXD0_GPIOx                       GPIOC
#define MX_ETH_RXD0_GPIO_PuPd                   GPIO_NOPULL
#define MX_MII_RXD0                             ETH_RXD0
#define MX_ETH_RXD0_GPIO_Pin                    GPIO_PIN_4
#define MX_ETH_RXD0_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_RXD0_GPIO_Mode                   GPIO_MODE_AF_PP
#define MX_ETH_RXD0_PinAttribute                CortexM7

/* Pin PC2 */
#define MX_ETH_TXD2_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_ETH_TXD2_Pin                         PC2
#define MX_ETH_TXD2_GPIOx                       GPIOC
#define MX_ETH_TXD2_GPIO_PuPd                   GPIO_NOPULL
#define MX_MII_TXD2                             ETH_TXD2
#define MX_ETH_TXD2_GPIO_Pin                    GPIO_PIN_2
#define MX_ETH_TXD2_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_TXD2_GPIO_Mode                   GPIO_MODE_AF_PP
#define MX_ETH_TXD2_PinAttribute                CortexM7

/* Pin PC5 */
#define MX_ETH_RXD1_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_ETH_RXD1_Pin                         PC5
#define MX_ETH_RXD1_GPIOx                       GPIOC
#define MX_ETH_RXD1_GPIO_PuPd                   GPIO_NOPULL
#define MX_MII_RXD1                             ETH_RXD1
#define MX_ETH_RXD1_GPIO_Pin                    GPIO_PIN_5
#define MX_ETH_RXD1_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_RXD1_GPIO_Mode                   GPIO_MODE_AF_PP
#define MX_ETH_RXD1_PinAttribute                CortexM7

/* Pin PG11 */
#define MX_ETH_TX_EN_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_ETH_TX_EN_Pin                        PG11
#define MX_ETH_TX_EN_GPIOx                      GPIOG
#define MX_ETH_TX_EN_GPIO_PuPd                  GPIO_NOPULL
#define MX_MII_TX_EN                            ETH_TX_EN
#define MX_ETH_TX_EN_GPIO_Pin                   GPIO_PIN_11
#define MX_ETH_TX_EN_GPIO_AF                    GPIO_AF11_ETH
#define MX_ETH_TX_EN_GPIO_Mode                  GPIO_MODE_AF_PP
#define MX_ETH_TX_EN_PinAttribute               CortexM7

/* Pin PG12 */
#define MX_ETH_TXD1_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_ETH_TXD1_Pin                         PG12
#define MX_ETH_TXD1_GPIOx                       GPIOG
#define MX_ETH_TXD1_GPIO_PuPd                   GPIO_NOPULL
#define MX_ETH_TXD1_GPIO_Pin                    GPIO_PIN_12
#define MX_ETH_TXD1_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_TXD1_GPIO_Mode                   GPIO_MODE_AF_PP
#define MX_ETH_TXD1_PinAttribute                CortexM7

/* Pin PG13 */
#define MX_ETH_TXD0_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_ETH_TXD0_Pin                         PG13
#define MX_ETH_TXD0_GPIOx                       GPIOG
#define MX_ETH_TXD0_GPIO_PuPd                   GPIO_NOPULL
#define MX_ETH_TXD0_GPIO_Pin                    GPIO_PIN_13
#define MX_ETH_TXD0_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_TXD0_GPIO_Mode                   GPIO_MODE_AF_PP
#define MX_ETH_TXD0_PinAttribute                CortexM7

/* Pin PC1 */
#define MX_ETH_MDC_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_ETH_MDC_Pin                          PC1
#define MX_ETH_MDC_GPIOx                        GPIOC
#define MX_ETH_MDC_GPIO_PuPd                    GPIO_NOPULL
#define MX_MII_MDC                              ETH_MDC
#define MX_ETH_MDC_GPIO_Pin                     GPIO_PIN_1
#define MX_ETH_MDC_GPIO_AF                      GPIO_AF11_ETH
#define MX_ETH_MDC_GPIO_Mode                    GPIO_MODE_AF_PP
#define MX_ETH_MDC_PinAttribute                 CortexM7

/* Pin PC3 */
#define MX_ETH_TX_CLK_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_ETH_TX_CLK_Pin                       PC3
#define MX_ETH_TX_CLK_GPIOx                     GPIOC
#define MX_ETH_TX_CLK_GPIO_PuPd                 GPIO_NOPULL
#define MX_MII_TX_CLK                           ETH_TX_CLK
#define MX_ETH_TX_CLK_GPIO_Pin                  GPIO_PIN_3
#define MX_ETH_TX_CLK_GPIO_AF                   GPIO_AF11_ETH
#define MX_ETH_TX_CLK_GPIO_Mode                 GPIO_MODE_AF_PP
#define MX_ETH_TX_CLK_PinAttribute              CortexM7

/* Pin PH2 */
#define MX_ETH_CRS_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_ETH_CRS_Pin                          PH2
#define MX_ETH_CRS_GPIOx                        GPIOH
#define MX_ETH_CRS_GPIO_PuPd                    GPIO_NOPULL
#define MX_ETH_CRS_GPIO_Pin                     GPIO_PIN_2
#define MX_ETH_CRS_GPIO_AF                      GPIO_AF11_ETH
#define MX_ETH_CRS_GPIO_Mode                    GPIO_MODE_AF_PP
#define MX_ETH_CRS_PinAttribute                 CortexM7

/* Pin PA1 */
#define MX_ETH_RX_CLK_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_ETH_RX_CLK_Pin                       PA1
#define MX_ETH_RX_CLK_GPIOx                     GPIOA
#define MX_ETH_RX_CLK_GPIO_PuPd                 GPIO_NOPULL
#define MX_MII_RX_CLK                           ETH_RX_CLK
#define MX_ETH_RX_CLK_GPIO_Pin                  GPIO_PIN_1
#define MX_ETH_RX_CLK_GPIO_AF                   GPIO_AF11_ETH
#define MX_ETH_RX_CLK_GPIO_Mode                 GPIO_MODE_AF_PP
#define MX_ETH_RX_CLK_PinAttribute              CortexM7

/* Pin PA2 */
#define MX_ETH_MDIO_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_ETH_MDIO_Pin                         PA2
#define MX_ETH_MDIO_GPIOx                       GPIOA
#define MX_ETH_MDIO_GPIO_PuPd                   GPIO_NOPULL
#define MX_MII_MDIO                             ETH_MDIO
#define MX_ETH_MDIO_GPIO_Pin                    GPIO_PIN_2
#define MX_ETH_MDIO_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_MDIO_GPIO_Mode                   GPIO_MODE_AF_PP
#define MX_ETH_MDIO_PinAttribute                CortexM7

/* Pin PA7 */
#define MX_ETH_RX_DV_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_ETH_RX_DV_Pin                        PA7
#define MX_ETH_RX_DV_GPIOx                      GPIOA
#define MX_ETH_RX_DV_GPIO_PuPd                  GPIO_NOPULL
#define MX_MII_RX_DV                            ETH_RX_DV
#define MX_ETH_RX_DV_GPIO_Pin                   GPIO_PIN_7
#define MX_ETH_RX_DV_GPIO_AF                    GPIO_AF11_ETH
#define MX_ETH_RX_DV_GPIO_Mode                  GPIO_MODE_AF_PP
#define MX_ETH_RX_DV_PinAttribute               CortexM7

/* Pin PH3 */
#define MX_ETH_COL_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_ETH_COL_Pin                          PH3
#define MX_ETH_COL_GPIOx                        GPIOH
#define MX_ETH_COL_GPIO_PuPd                    GPIO_NOPULL
#define MX_ETH_COL_GPIO_Pin                     GPIO_PIN_3
#define MX_ETH_COL_GPIO_AF                      GPIO_AF11_ETH
#define MX_ETH_COL_GPIO_Mode                    GPIO_MODE_AF_PP
#define MX_ETH_COL_PinAttribute                 CortexM7

/* Pin PI10 */
#define MX_ETH_RX_ER_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_ETH_RX_ER_Pin                        PI10
#define MX_ETH_RX_ER_GPIOx                      GPIOI
#define MX_ETH_RX_ER_GPIO_PuPd                  GPIO_NOPULL
#define MX_ETH_RX_ER_GPIO_Pin                   GPIO_PIN_10
#define MX_ETH_RX_ER_GPIO_AF                    GPIO_AF11_ETH
#define MX_ETH_RX_ER_GPIO_Mode                  GPIO_MODE_AF_PP
#define MX_ETH_RX_ER_PinAttribute               CortexM7

/* NVIC Configuration */

/* NVIC ETH_IRQn */
#define MX_ETH_IRQn_interruptPremptionPriority  0
#define MX_ETH_IRQn_PriorityGroup               NVIC_PRIORITYGROUP_4
#define MX_ETH_IRQn_Subriority                  0

/*-------------------------------- NVIC1      --------------------------------*/

#define MX_NVIC1                                1

/* GPIO Configuration */

/*-------------------------------- NVIC2      --------------------------------*/

#define MX_NVIC2                                1

/* GPIO Configuration */

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

#endif  /* __MX_DEVICE_H */

