
/*
 * Copyright (C) 2017 iCub Facility - Istituto Italiano di Tecnologia
 * Author:  Marco Accame
 * email:   marco.accame@iit.it
 * website: www.robotcub.org
 * Permission is granted to copy, distribute, and/or modify this program
 * under the terms of the GNU General Public License, version 2 or any
 * later version published by the Free Software Foundation.
 *
 * A copy of the license can be found at
 * http://www.robotcub.org/icub/license/gpl.txt
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
 * Public License for more details
*/

// - include guard ----------------------------------------------------------------------------------------------------

#ifndef _EMBOT_HW_SYS_H_
#define _EMBOT_HW_SYS_H_

#include "embot_core.h"
#include "embot_hw_types.h"
#include <string>



namespace embot { namespace hw { namespace sys {
       
    // retrieves the specified clock speed    
    std::uint32_t clock(embot::hw::CLOCK clk);
    
    // forces a reset
    void reset();
    
    // checks if at address there is a valid image to jump to
    bool canjump2address(std::uint32_t address);
    
    // it jumps to an image. if it returns ... means that canjump2address() id false
    void jump2address(std::uint32_t address); 
    
    // relocates the vector table
    void relocatevectortable(std::uint32_t offset);
   
    // they provide random numbers generated by hw    
    std::uint32_t random();    
    std::uint32_t minrandom();
    std::uint32_t maxrandom();
    
    // prints on the trace port. 
    // [[deprecated( "use embot::core::print()" )]] 
    int puts(const char* str);
    // [[deprecated( "use embot::core::print()" )]] 
    int puts(const std::string &str);
    
    // forces the cpu to exec instructions to reach a given delay
    void delay(embot::core::relTime t);    
    
}}} // namespace embot { namespace hw { namespace sys {




#endif  // include-guard


// - end-of-file (leave a blank line after)----------------------------------------------------------------------------


