
/*
 * Copyright (C) 2026 MESH - Istituto Italiano di Tecnologia
 * Author:  Marco Accame
 * email:   marco.accame@iit.it
*/

// - include guard ----------------------------------------------------------------------------------------------------

#ifndef __EMBOT_HW_MOTOR_BLDC_ENC_BSP_H_
#define __EMBOT_HW_MOTOR_BLDC_ENC_BSP_H_


#include "embot_hw_motor_bldc_enc.h"
#include "embot_hw_types.h"
#include "embot_hw_bsp.h"
#include "embot_hw_gpio.h"
#include <array>



namespace embot::hw::motor::bldc::enc::bsp {
    

    struct PROP
    {    
        uint8_t nothing {0};
        constexpr PROP() = default;
        constexpr PROP(const uint8_t n) : nothing(n) {}
    };    
            
    struct BSP : public embot::hw::bsp::SUPP
    {
        constexpr static std::uint8_t maxnumberof = embot::core::tointegral(embot::hw::MOTOR::maxnumberof);
        constexpr BSP(std::uint32_t msk, std::array<const PROP*, maxnumberof> pro) : SUPP(msk), properties(pro) {}
        constexpr BSP() : SUPP(0), properties({0}) {}            

        std::array<const PROP*, maxnumberof> properties;    
        constexpr const PROP * getPROP(embot::hw::MOTOR m) const { return supported(m) ? properties[embot::core::tointegral(m)] : nullptr; }
            
        bool init(embot::hw::MOTOR m) const;
        bool deinit(embot::hw::MOTOR m) const; 
        bool start(embot::hw::MOTOR m, const Mode &mo) const;        
        bool stop(embot::hw::MOTOR m) const;
        
        // naming convention:
        // - pulse is an event generated by a crossing of A or B
        // - revolution is a complete rotation of 360 degrees
        // - the resolution of the QENC in datasheet is expressed in pulses-per-revolution 
        // - the internal implementation makes the TIM register to be incremented / decremented with a step of
        //   2 ore 4 ticks at each AB detection.
        //   this step is is called ticks-per-pulse.
        // - ticks express the accumulation of values of the TIM register across multiple turns. 
        //   It is a a multiple of ticks-per-pulse, increases with clockwise rotation and decreases anticlockwise.
        // - angle is the cumulative angle since start() is called. So, suppose that start() is called when rotor is
        //   90 degrees off the stator, then when a clockwise rotation meets the Z index angle() is +270 degrees.
        //   And if instead we go anticlockwise angle() is -90 degrees when we meet the Z index.
        //   angle is related to ticks in this way:
        //   angle = ticks * (360.0 / ( ticksperpulse * pulsesperrevolution ))    
        
        uint32_t pulsesperrevolution(embot::hw::MOTOR m) const; // gets the Mode::resolution in pulses per revolution (PPR in datasheet)
        uint8_t ticksperpulse(embot::hw::MOTOR m) const;        // gets the internally used ticksperpulse (2 or 4)       
        int64_t ticks(embot::hw::MOTOR m) const;                // cumulative timer ticks (multiple of ticksperpulse)
        int64_t pulses(embot::hw::MOTOR m) const;               // number of AB pulses
        int64_t indexcrossings(embot::hw::MOTOR m) const;       // cumulative index Z crossing
        float angle(embot::hw::MOTOR m, AngleQE a) const; 
    };
    
    const BSP& getBSP();   
    
                      
} // namespace embot::hw::motor::bldc::enc::bsp {


namespace embot::hw::motor::bldc::enc::bsp::stm32 {
 
    // these must be called inside the global extern C functions that have a TIM_HandleTypeDef* argument
    void HAL_TIM_IC_MspInit(void *p);             
    void HAL_TIM_IC_MspDeInit(void *p);          
    
    void HAL_TIM_Encoder_MspInit(void *p);  
    void HAL_TIM_Encoder_MspDeInit(void *p);
    
} // namespace embot::hw::motor::bldc::adc::enc::stm32 {


#endif  // include-guard


// - end-of-file (leave a blank line after)----------------------------------------------------------------------------

